[package]
name = "mb-runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
mb-dom = { path = "../mb-dom" }
mb-engine = { path = "../mb-engine" }
rquickjs = { version = "0.11", features = ["macro"] }
selectors = "0.37"
tokio = { version = "1", default-features = false, features = ["rt", "rt-multi-thread"] }
ureq = "3"
url = "2"

[dev-dependencies]
image = { version = "0.25", default-features = false, features = ["png"] }
